# Generated by Django 5.2.17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepage_logo_linkhome'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiapage',
            name='autor',
            field=models.CharField(
                blank=True,
                help_text="Ex.: 'Dc. Júlio'.",
                max_length=150,
                verbose_name='Autor',
            ),
        ),
        migrations.CreateModel(
            name='NoticiaGaleriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='cms.noticiapage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
