# Generated by Django 5.2.17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('cms', '0003_noticia_autor_galeria'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('categoria', models.CharField(blank=True, choices=[('intercambio', 'Intercâmbio'), ('conclave', 'Conclave'), ('torneio', 'Torneio'), ('culto', 'Culto')], max_length=30)),
                ('local', models.CharField(blank=True, help_text="Ex.: 'Igreja Batista Videira de Nilópolis' ou 'Quadra Municipal'. Sem necessidade de endereço completo.", max_length=200, verbose_name='Local')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição curta')),
                ('imagem_capa', models.ForeignKey(blank=True, help_text='Opcional — se vazio, usa a primeira foto do álbum (abaixo) como capa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AlbumFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cms.albumpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
