# Generated by Django 5.2.17 on 2026-09-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpage',
            name='categoria',
            field=models.CharField(blank=True, choices=[('conclave', 'Conclave'), ('congresso', 'Congresso'), ('culto', 'Culto'), ('evangelismo', 'Evangelismo'), ('intercambio', 'Intercâmbio'), ('torneio', 'Torneio')], max_length=30),
        ),
    ]
