# Generated by Django 5.2.17 on 2026-09-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_albumpage_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpage',
            name='categoria',
            field=models.CharField(blank=True, choices=[('intercambio', 'Intercâmbio'), ('conclave', 'Conclave'), ('evangelismo', 'Evangelismo'), ('culto', 'Culto'), ('torneio', 'Torneio'), ('congresso', 'Congresso')], max_length=30),
        ),
    ]
