# Generated by Django 5.0.14 on 2026-09-05 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contato_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome do contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do contato')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Embaixada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('igreja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='embaixada', to='core.igreja')),
            ],
            options={
                'verbose_name': 'Embaixada',
                'verbose_name_plural': 'Embaixadas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/')),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=200, verbose_name='Nome do responsável')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, verbose_name='Telefone do responsável')),
                ('ativo', models.BooleanField(default=True)),
                ('embaixada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='core.embaixada')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diretoria', 'Diretoria'), ('conselheiro', 'Conselheiro'), ('embaixador_do_rei', 'Embaixador do Rei')], max_length=30)),
                ('cargo_diretoria', models.CharField(blank=True, choices=[('coordenador', 'Coordenador'), ('presidente', 'Presidente'), ('primeiro_secretario', '1º Secretário'), ('segundo_secretario', '2º Secretário'), ('diretor_midia_comunicacao', 'Diretor de Mídia e Comunicação'), ('diretor_esportes', 'Diretor de Esportes')], help_text='Preencher apenas quando tipo = Diretoria.', max_length=40, null=True, verbose_name='Cargo na diretoria')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='embaixada',
            name='conselheiro_responsavel',
            field=models.ForeignKey(blank=True, help_text="Deve ser uma Pessoa com Papel do tipo 'conselheiro'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embaixadas_lideradas', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='Carteirinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('validade', models.DateField()),
                ('emitida_em', models.DateField(auto_now_add=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteirinha', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Carteirinha',
                'verbose_name_plural': 'Carteirinhas',
            },
        ),
    ]
