# Generated by Django 5.2.17 on 2026-09-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='embaixada',
            name='conselheiros',
            field=models.ManyToManyField(blank=True, help_text='Demais conselheiros desta embaixada, além do responsável acima.', related_name='embaixadas_como_conselheiro', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='embaixada',
            name='conselheiro_responsavel',
            field=models.ForeignKey(blank=True, help_text="Deve ser uma Pessoa com Papel do tipo 'conselheiro'. É quem cadastra embaixadores e auxiliares desta embaixada.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embaixadas_lideradas', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='HorarioReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10, verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('embaixada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_reuniao', to='core.embaixada')),
            ],
            options={
                'verbose_name': 'Horário de reunião',
                'verbose_name_plural': 'Horários de reunião',
                'ordering': ['embaixada', 'dia_semana', 'horario'],
            },
        ),
    ]
