# Generated by Django 5.2.17 on 2026-09-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='embaixada',
            name='dia_semana_reuniao',
            field=models.CharField(blank=True, choices=[('domingo', 'Domingo'), ('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10, verbose_name='Dia da semana da reunião'),
        ),
        migrations.AddField(
            model_name='embaixada',
            name='horario_reuniao',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da reunião'),
        ),
    ]
