# Generated by Django 5.2.17 on 2026-09-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_embaixada_conselheiros_and_more'),
        ('core', '0003_embaixada_dia_semana_reuniao_and_more'),
    ]

    operations = [
    ]
