# Generated by Django 5.2.17 on 2026-09-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260915_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embaixada',
            name='dia_semana_reuniao',
        ),
        migrations.RemoveField(
            model_name='embaixada',
            name='horario_reuniao',
        ),
    ]
