# Generated by Django 5.2.17 on 2026-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remover_papel_e_conselheiro_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False, help_text='Senha temporária definida por um admin: trocar no primeiro acesso.'),
        ),
        migrations.AddField(
            model_name='membro',
            name='versao_token',
            field=models.PositiveIntegerField(default=0, help_text='Incrementar invalida todos os tokens já emitidos.'),
        ),
    ]
