# Generated by Django 5.2.17 on 2026-10-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membro_deve_trocar_senha_membro_versao_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
