# Generated by Django 5.2.17 on 2026-10-03 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_membro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoriaembaixada',
            name='cargo',
            field=models.CharField(choices=[('embaixador_chefe', 'Embaixador Chefe'), ('embaixador_assistente', 'Embaixador Assistente'), ('secretario', 'Secretário'), ('intendente', 'Intendente'), ('porta_voz', 'Porta-voz'), ('tesoureiro', 'Tesoureiro'), ('diretor_musica', 'Diretor de Música'), ('diretor_esportes', 'Diretor de Esportes')], max_length=30),
        ),
        migrations.CreateModel(
            name='Consulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('consul', models.OneToOneField(blank=True, help_text='Líder do consulado. Precisa ser Embaixador do Rei da mesma embaixada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulado_liderado', to='core.membro')),
                ('embaixada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulados', to='core.embaixada')),
            ],
            options={
                'verbose_name': 'Consulado',
                'verbose_name_plural': 'Consulados',
                'ordering': ['embaixada', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='consulado',
            field=models.ForeignKey(blank=True, help_text='Só para Embaixadores do Rei; opcional (nem toda embaixada tem consulados).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes', to='core.consulado'),
        ),
        migrations.AddConstraint(
            model_name='consulado',
            constraint=models.UniqueConstraint(fields=('embaixada', 'nome'), name='unico_nome_consulado_por_embaixada'),
        ),
    ]
