# Generated by Django 5.2.17 on 2026-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_diretoriaembaixada_cargo_consulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='adaptacoes',
            field=models.CharField(blank=True, help_text='Preencher apenas quando tipo = Embaixador do Rei. Registre a adaptação necessária (ex.: tempo adicional em provas escritas), não o diagnóstico.', max_length=300, verbose_name='Adaptações'),
        ),
    ]
