# Generated by Django 5.2.17 on 2026-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_membro_adaptacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igreja',
            name='contato_nome',
        ),
        migrations.RemoveField(
            model_name='igreja',
            name='contato_telefone',
        ),
        migrations.AddField(
            model_name='igreja',
            name='nome_pastor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do pastor'),
        ),
        migrations.AddField(
            model_name='igreja',
            name='telefone_pastor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do pastor'),
        ),
    ]
